### ISSUE TITLE
LateInitializationError: Field 'fileId' has not been initialized

### ISSUE THREAD

**Issue by ElectrifyPowr** [Viktoriaschule/dart-nextcloud#46] opened 2021-07-08 07:59 UTC
I want to be able to get the `fileId` of a `WebDavFile`.

I first loaded the files:
```Dart
//... 
var ncClient = NextCloudClient.withCredentials(Uri(host: baseUrl), "my@email.com", "myPassword");
//...
List<WebDavFile> allFiles = await ncClient.webDav.ls(path, props: WebDavProps.all);
```

Afterwards when I want to access the `fileId`:
```Dart
print(allFiles[index].fileId); //throws LateInit error

var res = await ncClient.webDav.getProps("/Documents/file.png", props: WebDavProps.all);
print(res.fileId); //throws LateInit error
```
And I get the following error: `LateInitializationError: Field 'fileId' has not been initialized`

Under the [Nextcloud WebDAV API for **Requesting Properties**](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#listing-folders-rfc4918) I saw that the `fileId` was defined as `<oc:fileid />`.
So I also tried to get the Property manually with `getOtherProp()` but I'm not quite sure if I used it correctly:
```Dart
print(allFiles[idx].getOtherProp('fileid', "http://owncloud.org/ns")); //returns null
print(allFiles[idx].getOtherProp('oc:fileid', "http://owncloud.org/ns")); //returns null
print(allFiles[idx].getOtherProp('fileid', "oc")); //returns null
```

I also looked at other properties. The following properties apart from `fileId` also threw a LateInit error:
`note, createdDate, uploadedDate`

Any help or fixing of the LateInit error would be appreciated.

**Comment by provokateurin** [comment] 2021-07-08 09:49
I can reproduce your issue. I'll see if I can fix it. To me it looks like the fileid isn't read properly and therefore doesn't get initialized correctly.

**Comment by provokateurin** [comment] 2021-07-08 10:08
The XML I get in the test is the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:nc="http://nextcloud.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
   <d:response>
      <d:href>/remote.php/dav/files/admin/dart-nextcloud-tests/prop-test.txt</d:href>
      <d:propstat>
         <d:prop>
            <d:getcontentlength>15</d:getcontentlength>
            <d:getcontenttype>text/plain</d:getcontenttype>
            <d:getetag>"483f3d3df855283b90fe4811c3fd75ee"</d:getetag>
            <d:getlastmodified>Thu, 08 Jul 2021 11:52:44 GMT</d:getlastmodified>
            <d:resourcetype />
            <nc:creation_time>0</nc:creation_time>
            <nc:has-preview>true</nc:has-preview>
            <nc:mount-type />
            <nc:note />
            <nc:sharees />
            <nc:upload_time>1625745164</nc:upload_time>
            <oc:comments-count>0</oc:comments-count>
            <oc:comments-href>/remote.php/dav/comments/files/61</oc:comments-href>
            <oc:comments-unread>0</oc:comments-unread>
            <oc:downloadURL />
            <oc:favorite>0</oc:favorite>
            <oc:id>00000061oc73reh23tgv</oc:id>
            <oc:owner-display-name>admin</oc:owner-display-name>
            <oc:owner-id>admin</oc:owner-id>
            <oc:permissions>RGDNVW</oc:permissions>
            <oc:share-types />
            <oc:size>15</oc:size>
            <oc:tags />
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
      <d:propstat>
         <d:prop>
            <nc:data-fingerprint />
            <nc:is-encrypted />
            <nc:metadata_etag />
            <nc:rich-workspace />
            <oc:checksums />
            <oc:circle />
            <oc:fileId />
            <oc:systemtag />
         </d:prop>
         <d:status>HTTP/1.1 404 Not Found</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>
```

`oc:fileId` is inside the 404 block so it seems like that file doesn't have a `fileId`.

If you need the just a unique id you can used the `oc:id` that is even globally unique.

**Comment by provokateurin** [comment] 2021-07-08 10:09
The PR only fixes the LateInit which definitely is a bug. It does nothing about the fact that the file has no `fileId` prop.

**Comment by ElectrifyPowr** [comment] 2021-07-08 11:26
> `oc:fileId` is inside the 404 block so it seems like that file doesn't have a `fileId`.
> 
> If you need the just a unique id you can used the `oc:id` that is even globally unique.

Unfortunately I need the `fileId`, not the `id`.
My goal was to display an image with the URL: `https://$_baseUrl/core/preview?fileId=$picture_id&x=$width&y=$height`, where the `fileId` is required.
I tried using the `id` but it did not work.

I know it works with the URL because I used it in Talk, where a message with a file had parameters with the `fileId`.

**Comment by ElectrifyPowr** [comment] 2021-07-08 11:28
> The PR only fixes the LateInit which definitely is a bug. It does nothing about the fact that the file has no `fileId` prop.

What would you suggest on how to replace the `fileId` then or get it in a different manner?
As I mentioned, with Talk, a message contained the `fileId`. Is this then maybe an issue on the side of Nextcloud?

**Comment by provokateurin** [comment] 2021-07-08 11:31
I think it has to be a Nextcloud issue. If you do a curl you should get the same XML with the missing `fileId`. I'd suggest you search for some issues that might already be there or otherwise create an issue asking if it is the intended behavior/report the bug (and link to this)

**Comment by ElectrifyPowr** [comment] 2021-07-08 15:13
This btw also causes an error when you try to print a file with `print(theWebDavFile);` because it uses the `toString()` function, which wants to print all the variables.
So if a variable is `late` and still hasn't been initialized the `toString()` will cause the same error.

**Comment by ElectrifyPowr** [comment] 2021-07-08 15:13
> I think it has to be a Nextcloud issue. If you do a curl you should get the same XML with the missing `fileId`. I'd suggest you search for some issues that might already be there or otherwise create an issue asking if it is the intended behavior/report the bug (and link to this)

What curl call did you use as a reference?

**Comment by provokateurin** [comment] 2022-07-21 09:52
Fixed in https://github.com/jld3103/nextcloud-harbour/tree/main/packages/nextcloud/lib/src/clients/custom/webdav

**Closed as completed by provokateurin** 2022-07-21 09:52 UTC
